db:
  name: itemdb
eureka:
  client:
    serviceUrl:
      defaultZone: http://INPUHJPC04133:8761/eureka/
      
ui:
  serverUrl: http://localhost:4200/
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
spring:
  jmx:
    default-domain: Item-Service

chaos:
  monkey:
    enabled: true
    watcher:
      component: false
      controller: false
      repository: false
      rest-controller: true
      service: true