db:
  name: itemdb
eureka:
  client:
    serviceUrl:
      defaultZone: http://INPUHJPC04133:8761/eureka/
      
ui:
  serverUrl: http://localhost:4200/
management:
  endpoint:
    chaosmonkey:
      enabled: true
    chaosmonkeyjmx:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  metrics:
    enable: true
    tags:
      region: us-east-1
      stack: dev
spring:
  jmx:
    default-domain: Item-Service
  jpa:
    hibernate:
      ddl-auto: none

chaos:
  monkey:
    enabled: true
    assaults:
      latency-active: true
      latency-range-start: 1000
      latency-range-end: 4500
      level: 1
    watcher:
      controller: false
      restController: true
      service: true
      repository: false