server:
  port: 5052
db:
  name: itemdb
eureka:
  client:
    serviceUrl:
      defaultZone: http://INPUHJPC04133:8761/eureka/
      
ui:
  serverUrl: http://localhost:4200/
management:
  endpoints:
    web:
      exposure:
        include: '*'
spring:
  jmx:
    default-domain: Item-Service