server:
  port: 5053
db:
  name: salesorderdb
spring:
  kafka:
    bootstrap-servers: INPUHJPC04133:9092
    consumer:
      group-id: myGroup
  mail:
    host: localhost
    port: 25
  jmx:
    default-domain: SalesOrder-Service
eureka:
  client:
    serviceUrl:
      defaultZone: http://INPUHJPC04133:8761/eureka/
     
ui:
  serverUrl: http://localhost:4200/ 
management:
  endpoints:
    web:
      exposure:
        include: '*'